# http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/telemetry.html

S_ACTUATOR_CONTROL_TARGET = 'actuator_control_target'
S_ACTUATOR_OUTPUT_STATUS = 'actuator_output_status'
S_IS_ARMED = 'armed'
S_ATTITUDE_ANGULAR_VELOCITY_BODY = 'attitude_angular_velocity_body'
S_ATTITUDE_EULER = 'attitude_euler'
S_BATTERY = 'battery'
S_FIXEDWING_METRICS = 'fixedwing_metrics'
S_FLIGHT_MODE = 'flight_mode'
S_GPS_GLOBAL_ORIGIN = 'get_gps_global_origin'
S_GPS_INFO = 'gps_info'
S_GROUND_TRUTH = 'ground_truth'
S_HEALTH_STATUS = 'health'
S_HOME_POSITION = 'home'
S_IMU_UPDATES_NED = 'imu'
S_IS_IN_AIR = 'in_air'
S_IS_LANDED = 'landed_state'
S_POSITION = 'position'
S_POSITION_VELOCITY_NED = 'position_velocity_ned'
S_UNIX_TIME = 'unix_epoch_time'
S_STATUS_TEXT = 'status_text'
S_GROUND_SPEED_NED = 'velocity_ned'